### ISSUE TITLE
What to do after downloading?

### ISSUE THREAD

**Issue by guettli** [AnkitMItraOfficial/StackOverFlow-Clone#5]
In the README you say that you can download the software. But what next? How can I test it?

You know django, but many people don't know django yet :-)

**Comment by AnkitMitraOfficial** [comment]
That's their headache,they will download the code,when they want to test it

**Comment by AnkitMitraOfficial** [comment]
instructions -- cd Homesite
then runserver

**Comment by guettli** [comment]
You said "That's their headache".

Do you want new participants/users/customers/friends, or do you want to do it on your own?

Please think about what you wrote again.

**Comment by guettli** [comment]
Things should be like "Don't make me think". If the user needs to think, than it is not simple and it is likely that the user will walk away. Thinking hurts and you don't want them to have headache.

**Comment by guettli** [comment]
@AnkitMItraOfficial please elaborate the installing instructions. This is Schwarzenegger rule No. 6.

**Comment by AnkitMitraOfficial** [comment]
I have given full instructions now 😊👍

**Comment by guettli** [comment]
Please include the issue number in the commit message the next time. This makes it easier for me to see your changes.

**Comment by guettli** [comment]
I think this is not solved yet. For example: How does Django get installed (which is required to run `manage.py`)?

Dependencies are managed with `setup.py` in Python.

Please  have a loot at the docs about packaging: https://packaging.python.org/

**Comment by AnkitMitraOfficial** [comment]
> Please include the issue number in the commit message the next time. This makes it easier for me to see your changes.

Okay😊👍
