### ISSUE TITLE
Please remove pyc files from the git repo

### ISSUE THREAD

**Issue by guettli** [AnkitMItraOfficial/StackOverFlow-Clone#7]
These files should not be in a git repo, since the get created automatically.

**Comment by AnkitMitraOfficial** [comment]
Okay!

**Comment by guettli** [comment]
Here are still some: https://github.com/AnkitMItraOfficial/StackOverFlow-Clone/tree/main/Authentication/__pycache__

**Comment by AnkitMitraOfficial** [comment]
I removed all the .pyc files

**Comment by guettli** [comment]
Great. Thank you.
